const CONTACT = {
  email: "locprestige89@outlook.fr",
  snapchat: "krlocation",
  snapUrl: "https://www.snapchat.com/add/krlocation?share_id=SXHXNUFNSLO_61AMKYuJpw&locale=fr_BE",
};

const VEHICLES = [
  {
    id: "rs6",
    name: "Audi RS6 2021",
    category: "sportive",
    year: "2021",
    seats: 5,
    power: "600 ch",
    transmission: "Automatique",
    fuel: "Essence",
    km: 87240,
    priceWeek: 550,
    priceWeekend: 650,
    deposit: 5000,
    featured: true,
    booked: [],
    image: "images/rs6/avant.jpg?v=40",
    images: [
      "images/rs6/avant.jpg?v=40",
      "images/rs6/face.jpg?v=40",
      "images/rs6/profil.jpg?v=40",
      "images/rs6/trois-quarts.jpg?v=40",
      "images/rs6/arriere.jpg?v=40",
      "images/rs6/poste.jpg?v=40",
    ],
    blurb:
      "Un break de 600 chevaux. V8 4.0 biturbo, quattro, 0 à 100 en 3,6 s : la RS6 2021 n’est pas une voiture, c’est une fusée familiale. Gris mat, étriers rouges, Virtual Cockpit, tout l’arsenal RS. Pour un week-end, un événement, ou simplement sentir ce que 800 Nm veulent dire.",
  },
  {
    id: "m3",
    name: "BMW M3 G80 2023",
    category: "sportive",
    year: "2023",
    seats: 5,
    power: "510 ch",
    transmission: "Automatique",
    fuel: "Essence",
    km: 61480,
    price: 350,
    deposit: 4000,
    featured: true,
    booked: [{ from: "2026-08-30", to: "2026-09-05" }],
    image: "images/m3/avant.jpg?v=43",
    images: [
      "images/m3/avant.jpg?v=43",
      "images/m3/arriere.jpg?v=43",
      "images/m3/poste.jpg?v=40",
      "images/m3/sieges.jpg?v=40",
    ],
    blurb:
      "Une M3 G80 2023, gris métallisé. 510 ch, baquets carbone, volant M, iDrive 8. La berline qui sort des parkings comme d’un paddock. Pour un week-end, un événement, ou simplement sentir ce que ça veut dire M3.",
  },
  {
    id: "taycan",
    name: "Porsche Taycan 2022",
    category: "sportive",
    seats: 4,
    power: "476 ch",
    transmission: "Automatique",
    fuel: "Électrique",
    battery: "94 kW",
    year: "2022",
    km: 53890,
    price: 350,
    deposit: 3500,
    featured: true,
    booked: [{ from: "2026-08-31", to: "2026-09-06" }],
    image: "images/taycan/avant.jpg?v=40",
    images: [
      "images/taycan/avant.jpg?v=40",
      "images/taycan/trois-quarts.jpg?v=40",
      "images/taycan/profil-arriere.jpg?v=40",
      "images/taycan/arriere.jpg?v=40",
      "images/taycan/face.jpg?v=40",
      "images/taycan/poste.jpg?v=40",
      "images/taycan/habitacle.jpg?v=40",
    ],
    blurb:
      "Un Taycan 2022, blanc, 100 % électrique. 476 chevaux, batterie de 94 kW. Silence total, accélération immédiate, habitacle tout écran : le prestige Porsche sans moteur essence. Pour un week-end, un événement, ou simplement rouler dans autre chose.",
  },
  {
    id: "a45",
    name: "Mercedes A45 AMG",
    category: "sportive",
    seats: 5,
    power: "421 ch",
    transmission: "Automatique",
    fuel: "Essence",
    km: 72150,
    price: 280,
    deposit: 2500,
    featured: true,
    booked: [],
    image: "images/a45/trois-quarts.jpg?v=41",
    images: [
      "images/a45/trois-quarts.jpg?v=41",
      "images/a45/avant.jpg?v=41",
      "images/a45/habitacle.jpg?v=40",
      "images/a45/poste.jpg?v=40",
    ],
    blurb:
      "Une A45 AMG, gris métallisé. 421 ch, 4MATIC+, pack aéro, étriers rouges, grille Panamericana. Toit panoramique, baquets et volant Alcantara : la compacte qui envoie vraiment. Pour un week-end, un événement, ou simplement sentir la différence avec une GTI.",
  },
  {
    id: "cayenne",
    name: "Porsche Cayenne Coupé",
    category: "sportive",
    seats: 5,
    power: "340 ch",
    transmission: "Tiptronic S",
    fuel: "Essence",
    km: 94670,
    price: 200,
    featured: true,
    booked: [{ from: "2026-09-02", to: "2026-09-02" }],
    image: "images/cayenne/trois-quarts.jpg?v=40",
    images: [
      "images/cayenne/trois-quarts.jpg?v=40",
      "images/cayenne/face.jpg?v=40",
      "images/cayenne/arriere.jpg?v=40",
      "images/cayenne/trois-quarts-arriere.jpg?v=40",
      "images/cayenne/profil-arriere.jpg?v=40",
      "images/cayenne/poste.jpg?v=40",
      "images/cayenne/habitacle.jpg?v=40",
    ],
    blurb:
      "Un Cayenne Coupé, noir, 3.0 V6 340 ch, Tiptronic S. Toit panoramique, cuir, écran Porsche : le SUV qui roule comme une sportive. Pour un week-end, un événement, ou simplement partir plus haut.",
  },
  {
    id: "golf-gti",
    name: "Volkswagen Golf 8 GTI",
    category: "sportive",
    seats: 5,
    power: "245 ch",
    transmission: "Automatique",
    fuel: "Essence",
    km: 58320,
    price: 250,
    deposit: 3000,
    featured: true,
    booked: [{ from: "2026-09-02", to: "2026-09-02" }],
    image: "images/gti/avant.jpg?v=40",
    images: [
      "images/gti/avant.jpg?v=40",
      "images/gti/avant-2.jpg?v=40",
      "images/gti/arriere.jpg?v=40",
      "images/gti/profil.jpg?v=40",
      "images/gti/rue.jpg?v=40",
      "images/gti/interieur.jpg?v=40",
      "images/gti/phare.jpg?v=40",
    ],
    blurb:
      "La GTI qu’on attend : 245 ch, DSG, toit ouvrant, étriers rouges. Plus facile au quotidien que l’RS3, tout aussi fun sur route. Idéale pour un mariage, un départ en week-end ou se faire plaisir sans prendre un bolide trop extrême.",
  },
  {
    id: "panamera",
    name: "Porsche Panamera Hybride 2.9",
    category: "sportive",
    seats: 4,
    transmission: "Automatique",
    fuel: "Hybride",
    km: 80110,
    price: 250,
    deposit: 2500,
    featured: true,
    booked: [],
    image: "images/panamera/trois-quarts.jpg?v=40",
    images: [
      "images/panamera/trois-quarts.jpg?v=40",
      "images/panamera/avant.jpg?v=40",
      "images/panamera/arriere.jpg?v=40",
      "images/panamera/poste.jpg?v=40",
      "images/panamera/sieges-arriere.jpg?v=40",
    ],
    blurb:
      "Une Panamera Hybride 2.9, gris métallisé. Cuir cognac, toit ouvrant, étriers acid green : la berline Porsche qui avance en silence. Pour un week-end, un événement, ou simplement rouler autrement.",
  },
  {
    id: "rs3",
    name: "Audi RS3",
    category: "sportive",
    seats: 5,
    power: "400 ch",
    transmission: "Automatique",
    fuel: "Essence",
    km: 65740,
    price: 250,
    deposit: 2500,
    featured: true,
    booked: [],
    image: "images/rs3/avant-large.jpg?v=40",
    images: [
      "images/rs3/avant-large.jpg?v=40",
      "images/rs3/arriere.jpg?v=40",
      "images/rs3/sieges.jpg?v=40",
      "images/rs3/poste.jpg?v=40",
    ],
    blurb:
      "La star de la flotte. 400 ch, transmission quattro, gris Nardo et pack Black Optics. Sièges RS, toit panoramique : parfaite pour un week-end, un shooting ou simplement le plaisir de conduire. Son 5-cylindres est unique, on ne s’en lasse pas.",
  },
  {
    id: "classe-a",
    name: "Mercedes Classe A 2021",
    category: "citadine",
    year: "2021",
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    km: 76890,
    price: 85,
    deposit: 1000,
    featured: true,
    booked: [{ from: "2026-09-02", to: "2026-09-02" }],
    image: "images/classe-a/avant.jpg?v=40",
    images: [
      "images/classe-a/avant.jpg?v=40",
      "images/classe-a/face.jpg?v=40",
      "images/classe-a/trois-quarts.jpg?v=40",
      "images/classe-a/arriere.jpg?v=40",
      "images/classe-a/habitacle.jpg?v=40",
      "images/classe-a/poste.jpg?v=40",
      "images/classe-a/sieges.jpg?v=40",
    ],
    blurb:
      "Une Classe A 2021 AMG Line, blanche, toit panoramique. Double écran MBUX, habitacle cuir et surpiqûres rouges, éclairage d’ambiance : la citadine prestige pour la ville, un week-end ou un événement.",
  },
  {
    id: "208",
    name: "Peugeot 208 2024",
    category: "citadine",
    year: "2024",
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    km: 51260,
    price: 65,
    deposit: 800,
    featured: true,
    image: "images/208/trois-quarts.jpg?v=40",
    images: [
      "images/208/trois-quarts.jpg?v=40",
      "images/208/avant.jpg?v=40",
      "images/208/arriere.jpg?v=40",
      "images/208/poste.jpg?v=40",
    ],
    blurb:
      "Une 208 2024, noire, i-Cockpit et écran central. Compacte, récente, manuelle : la citadine pour la ville, un week-end ou un remplacement sans se prendre la tête.",
  },
  {
    id: "trafic",
    name: "Renault Trafic",
    category: "utilitaire",
    seats: 9,
    transmission: "Manuelle",
    fuel: "Diesel",
    km: 98340,
    price: 60,
    deposit: 500,
    featured: true,
    image: "images/trafic/avant.jpg?v=40",
    images: [
      "images/trafic/avant.jpg?v=40",
      "images/trafic/arriere.jpg?v=40",
      "images/trafic/sieges.jpg?v=40",
      "images/trafic/poste.jpg?v=40",
      "images/trafic/habitacle.jpg?v=40",
    ],
    blurb:
      "Un Trafic argenté, 9 places. Sièges cuir surpiqués, écran central, stores aux vitres : l’utilitaire pour un groupe, un événement ou simplement transporter du monde sans se serrer.",
  },
  {
    id: "bmw-116i",
    name: "BMW 116i Série 1 2025",
    category: "citadine",
    year: "2025",
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    km: 54780,
    price: 80,
    deposit: 1000,
    featured: true,
    booked: [{ from: "2026-09-01", to: "2026-09-02" }],
    image: "images/bmw-116i/trois-quarts.jpg?v=40",
    images: [
      "images/bmw-116i/trois-quarts.jpg?v=40",
      "images/bmw-116i/avant.jpg?v=40",
      "images/bmw-116i/face.jpg?v=40",
      "images/bmw-116i/arriere.jpg?v=40",
      "images/bmw-116i/poste.jpg?v=40",
      "images/bmw-116i/sieges.jpg?v=40",
    ],
    blurb:
      "Une Série 1 2025, noire, finition M Sport. 116i, automatique, écran incurvé, sièges sport : la citadine BMW récente pour la ville, un week-end ou un remplacement sans se prendre la tête.",
  },
];

const CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "sportive", label: "Sportives" },
  { id: "citadine", label: "Citadines" },
  { id: "utilitaire", label: "Utilitaires" },
];
